version: '2.2'
services:
  Database:
    image: postgis/postgis:14-3.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - '1234:5432'
    volumes:
      - ./Database/spots.sql:/docker-entrypoint-initdb.d/create_tables.sql
